name: CI on Linux

on:
  push:
    branches:
      # Push events to branches matching refs/heads/master
      - 'main'
  pull_request:

env:
  CMAKE_VERSION: 3.8.2
  SEQAN3_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -ex {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: "gcc11"
            cxx: "g++-11"
            cc: "gcc-11"
            build_type: Release

          - name: "gcc10"
            cxx: "g++-10"
            cc: "gcc-10"
            build_type: Release

    steps:
      - name: Set repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ env.REPOSITORY_NAME }}
          fetch-depth: 2
          submodules: recursive

      - name: Add package source
        run: bash ./${{ env.REPOSITORY_NAME }}/lib/seqan3/.github/workflows/scripts/configure_apt.sh

      - name: Install CMake
        run: bash ./${{ env.REPOSITORY_NAME }}/lib/seqan3/.github/workflows/scripts/install_cmake.sh

      - name: Install compiler ${{ matrix.cxx }}
        run: sudo apt-get install --yes ${{ matrix.cxx }}

      - name: Tool versions
        run: |
          env cmake --version
          env ${{ matrix.cxx }} --version

      - name: Configure tests
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: |
          mkdir build
          cd build
          cmake ../${{ env.REPOSITORY_NAME }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                                              -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}"

      - name: Build application
        run: |
          cd build
          make -k -j2
